#!/usr/bin/env python3
"""Convert the MAME 'starwars' or 'esb' (The Empire Strikes Back) ROM set into a C header for the ESP32 build.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

EXPECTED = {  # name: (size, crc32)
    # Star Wars
    '136021.102': (0x2000, 0xf725e344), '136021.203': (0x2000, 0xf6da0a00),
    '136021.104': (0x2000, 0x7e406703), '136021.206': (0x2000, 0xc7e51237),
    '136021.214': (0x4000, 0x04f1876e), '136021.105': (0x1000, 0x538e7d2f),
    '136021.110': (0x400, 0x810e040e), '136021.111': (0x400, 0xae69881c),
    '136021.112': (0x400, 0xecf22628), '136021.113': (0x400, 0x83febfde),
    '136021-105.1l': (0x100, 0x82fc3eb2),
    '136021.107': (0x2000, 0xdbf3aea2), '136021.208': (0x2000, 0xe38070a8),
    # The Empire Strikes Back
    '136031.101': (0x4000, 0xef1e3ae5), '136031.102': (0x4000, 0x62ce5c12),
    '136031.203': (0x4000, 0x27b0889b), '136031.104': (0x4000, 0xfd5c725e),
    '136031.105': (0x4000, 0xea9e4dce), '136031.106': (0x4000, 0x76d07f59),
    '136031.111': (0x1000, 0xb1f9bd12),
    '136031.113': (0x4000, 0x24ae3815), '136031.112': (0x4000, 0xca72d341),
    '136031.110': (0x400, 0xb8d0f69d), '136031.109': (0x400, 0x6a2a4d98),
    '136031.108': (0x400, 0x6a76138f), '136031.107': (0x400, 0xafbf6e01),
}

def load(romdir, name):
    data = (romdir / name).read_bytes()
    size, crc = EXPECTED[name]
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    if zlib.crc32(data) & 0xffffffff != crc:
        print(f'  warning: {name} crc32 {zlib.crc32(data):08x} != expected {crc:08x}')
    print(f'  {name}: {len(data)} bytes ok')
    return data

def c_array(name, data):
    lines = [f'static const uint8_t {name}[{len(data)}] = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i+16]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'esb')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    esb = (romdir / '136031.101').exists()
    if not esb:
        rom_main = load(romdir, '136021.102') + load(romdir, '136021.203') + load(romdir, '136021.104') + load(romdir, '136021.206')
        rom_bank = load(romdir, '136021.214')
        rom_vector = load(romdir, '136021.105')
        prom_math = b''.join(load(romdir, n) for n in ('136021.110', '136021.111', '136021.112', '136021.113'))
        prom_avg = load(romdir, '136021-105.1l')
        rom_sound = load(romdir, '136021.107') + load(romdir, '136021.208')
        rom_slapstic = None
        game = 'STARWARS'
    else:
        # The 16 KB program ROMs hold both pages of a bank in their two halves
        r102, r203, r104 = load(romdir, '136031.102'), load(romdir, '136031.203'), load(romdir, '136031.104')
        rom_main = r102[:0x2000] + r203[:0x2000] + r104[:0x2000] + r102[0x2000:] + r203[0x2000:] + r104[0x2000:]
        rom_bank = load(romdir, '136031.101')
        rom_slapstic = load(romdir, '136031.105') + load(romdir, '136031.106')
        rom_vector = load(romdir, '136031.111')
        prom_math = b''.join(load(romdir, n) for n in ('136031.110', '136031.109', '136031.108', '136031.107'))
        prom_avg = load(romdir, '136021-105.1l')
        s113, s112 = load(romdir, '136031.113'), load(romdir, '136031.112')
        rom_sound = s113[:0x2000] + s112[:0x2000] + s113[0x2000:] + s112[0x2000:]
        game = 'ESB'
    out = ['/* starwars_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef STARWARS_ROMS_H', '#define STARWARS_ROMS_H', '#include <stdint.h>', '',
           f'#define SW_GAME_{game} 1', '',
           c_array('sw_rom_main', rom_main), '', c_array('sw_rom_bank', rom_bank), '',
           c_array('sw_rom_vector', rom_vector), '', c_array('sw_prom_mathbox', prom_math), '',
           c_array('sw_prom_avg', prom_avg), '', c_array('sw_rom_sound', rom_sound), '']
    if rom_slapstic is not None:
        out += [c_array('sw_rom_slapstic', rom_slapstic), '']
    out += ['#endif']
    (outdir / 'starwars_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "starwars_roms.h"}')

if __name__ == '__main__':
    main()
